"""Package a registered agent and submit it to the Kaggriculture competition.

Kaggle runs submissions in a bare environment with no `kaggriculture` package
installed, so a bundle needs its own copy of the source alongside a `main.py`
that re-exports the chosen agent's `agent` function. This module builds that
bundle (vendoring `src/kaggriculture` verbatim) and shells out to the `kaggle`
CLI to submit it.
"""

import argparse
import shutil
import subprocess
import sys
import tarfile
from pathlib import Path

from kaggriculture.agents.registry import AGENTS

PACKAGE_DIR = Path(__file__).resolve().parent
DEFAULT_COMPETITION = "kaggriculture"
DEFAULT_OUTPUT_DIR = Path("dist")

MAIN_TEMPLATE = '''"""Kaggle submission entrypoint, generated by `kaggriculture-submit`.

The `kaggriculture` package is vendored alongside this file (see the sibling
`kaggriculture/` directory) so this import resolves exactly as it does in the
source repo.
"""

from {module} import agent  # noqa: F401
'''


def build_bundle(agent_name: str, output_dir: Path) -> Path:
    """Vendor the kaggriculture package plus a generated main.py, then tar.gz them.

    Returns the path to the built tarball.
    """
    agent_fn = AGENTS[agent_name]
    module = agent_fn.__module__

    output_dir.mkdir(parents=True, exist_ok=True)
    staging_dir = output_dir / f"{agent_name}-bundle"
    if staging_dir.exists():
        shutil.rmtree(staging_dir)
    staging_dir.mkdir(parents=True)

    shutil.copytree(
        PACKAGE_DIR,
        staging_dir / "kaggriculture",
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
    )
    (staging_dir / "main.py").write_text(MAIN_TEMPLATE.format(module=module))

    tarball = output_dir / f"{agent_name}.tar.gz"
    with tarfile.open(tarball, "w:gz") as tar:
        tar.add(staging_dir / "main.py", arcname="main.py")
        tar.add(staging_dir / "kaggriculture", arcname="kaggriculture")
    shutil.rmtree(staging_dir)
    return tarball


def local_smoke_test(agent_name: str, episode_steps: int) -> tuple[str, float, float]:
    """Run one local episode against the built-in `random` agent.

    Returns (status, agent_reward, opponent_reward). `status` is the
    kaggle-environments terminal status for the submitted agent's seat
    (e.g. "DONE", "ERROR", "INVALID").
    """
    from kaggle_environments import make

    env = make("kaggriculture", configuration={"episodeSteps": episode_steps}, debug=True)
    env.run([AGENTS[agent_name], "random"])
    final = env.steps[-1]
    return (
        final[0].status,
        float(final[0].reward or 0.0),
        float(final[1].reward or 0.0),
    )


def smoke_test_passes(status: str, reward: float, opponent_reward: float) -> bool:
    """Decide whether a smoke-test episode clears the bar for submission.

    TODO(you): this is a judgment call, not a mechanical check. A single
    episode against `random` is noisy, so consider tightening this before
    relying on it: do you need to beat `random` at all, or just confirm the
    agent doesn't crash (status != "ERROR"/"INVALID")? Is there a minimum
    reward below which the agent is effectively doing nothing? Should you
    run a handful of seeds instead of one before trusting the result?

    Current default: only blocks on a crash/invalid-action status.
    """
    return status == "DONE"


def submit(tarball: Path, competition: str, message: str) -> None:
    if shutil.which("kaggle") is None:
        print(
            "error: the `kaggle` CLI is not on PATH. Install it with `pip install kaggle` "
            "and set up credentials (see AGENTS.md).",
            file=sys.stderr,
        )
        raise SystemExit(1)
    subprocess.run(
        [
            "kaggle",
            "competitions",
            "submit",
            competition,
            "-f",
            str(tarball),
            "-m",
            message,
        ],
        check=True,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("agent", choices=sorted(AGENTS), help="Registered agent name to submit")
    parser.add_argument("-m", "--message", required=True, help="Submission message")
    parser.add_argument("--competition", default=DEFAULT_COMPETITION)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument(
        "--smoke-test",
        action="store_true",
        help="Run one local episode vs `random` before submitting",
    )
    parser.add_argument("--smoke-test-steps", type=int, default=200)
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Build the submission bundle but do not call `kaggle submit`",
    )
    args = parser.parse_args()

    if args.smoke_test:
        print(f"Running local smoke test ({args.smoke_test_steps} steps) vs random...")
        status, reward, opponent_reward = local_smoke_test(args.agent, args.smoke_test_steps)
        print(f"  status={status} reward={reward:.0f} vs random={opponent_reward:.0f}")
        if not smoke_test_passes(status, reward, opponent_reward):
            print("Smoke test gate failed; rerun without --smoke-test to force.", file=sys.stderr)
            raise SystemExit(1)

    tarball = build_bundle(args.agent, args.output_dir)
    print(f"Built {tarball} ({tarball.stat().st_size:,} bytes)")

    if args.dry_run:
        print("Dry run: skipping `kaggle competitions submit`.")
        return

    submit(tarball, args.competition, args.message)


if __name__ == "__main__":
    main()
